"""Updated the workoutexercise relationship to workoutexercises

Revision ID: 1586eb4e3c61
Revises: aa823cf40036
Create Date: 2026-08-02 21:43:55.382778

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1586eb4e3c61'
down_revision = 'aa823cf40036'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workouts', schema=None) as batch_op:
        batch_op.alter_column('date',
               existing_type=sa.DATE(),
               type_=sa.Text(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workouts', schema=None) as batch_op:
        batch_op.alter_column('date',
               existing_type=sa.Text(),
               type_=sa.DATE(),
               existing_nullable=False)

    # ### end Alembic commands ###
