"""made the foreign keys in the workoutexercises model not nullable

Revision ID: aa823cf40036
Revises: 1c73edb8710f
Create Date: 2026-07-27 22:43:26.042438

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa823cf40036'
down_revision = '1c73edb8710f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workoutexercises', schema=None) as batch_op:
        batch_op.alter_column('workout_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('exercise_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workoutexercises', schema=None) as batch_op:
        batch_op.alter_column('exercise_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('workout_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
